version = 0.1
[default.deploy.parameters]
stack_name = "infrastructure"
resolve_s3 = true
s3_prefix = "infrastructure"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "CallbackUrl=\"http://localhost\""
image_repositories = []
