version = 0.1
[default.deploy.parameters]
stack_name = "myapp"
resolve_s3 = true
s3_prefix = "myapp"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "CallbackUrl=\"http://localhost\""
image_repositories = []

[default.list_stack_outputs.parameters]
stack_name = "myapp-cognito-H0ONOVL9M30L"
output = "json"
