AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Module 4 start state

Parameters:
  CallbackUrl:
    Type: String

Resources:
  cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml
      Parameters:
        CallbackUrl: !Ref CallbackUrl

  users:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./users/template.yaml
      Parameters: 
        CognitoUserPool: !GetAtt cognito.Outputs.CognitoUserPoolId
