AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns -  User Pool (uksb-1tthgi812) (tag:cognito-user-pool)

Parameters:
  CallbackUrl:
    Type: String
    Description: Callback URL

Resources:
  
  #################################################################
  #  User Pool ##############################################
  # ################################################################

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      UserPoolName: cognito-user-pool-userpool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      AllowedOAuthFlows: 
        - implicit
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes: 
        - email
        - openid
        - profile
      CallbackURLs: 
        - !Ref CallbackUrl
      ClientName: cognito-user-pool-client
      SupportedIdentityProviders: 
        - COGNITO
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  UserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties: 
      Identifier: com.apigw
      Name: com.apigw
      Scopes: 
        - ScopeDescription: scope_description
          ScopeName: scope_name
      UserPoolId: !Ref UserPool
      
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: !Sub user-pool-domain-${AWS::AccountId}
      UserPoolId: !Ref UserPool

  UserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Administrators
      Description: "Administrators group"
      UserPoolId: !Ref UserPool


Outputs:

  HostedUi:
    Description: Hosted UI
    Value: !Sub "https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=token&scope=email+openid+profile&redirect_uri=${CallbackUrl}"

  UserPoolAdminGroupId:
    Description:  User Pool Admin Group ID
    Value: !Ref UserPoolAdminGroup

  UserPoolId:
    Description:  User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description:  User Pool Client ID
    Value: !Ref UserPoolClient

  UserPoolDomain:
    Description:  User Pool Domain
    Value: !Sub "${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
