version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-users"
resolve_s3 = true
s3_prefix = "sam-app-users"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPool=\"eu-north-1_e5hfHtSsn\" AdministratorsLambdaAuthorizer=\"infrastructure-AdministratorsLambdaAuthorizer-3hVNfZO2RgGA\""
image_repositories = []
