AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Cognito User Pool and Lambda Authorizer (uksb-1tthgi812) (tag:cognito-lambda-authorizer)

Parameters:
  CognitoUserPool:
    Type: String
    Description: Cognito User Pool ARN

  AdministratorsLambdaAuthorizer:
    Type: String
    Description: Administrators Lambda Authorizer

Globals:
  Function:
    Runtime: python3.12
    CodeUri: src

  Api:
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers: 
        CognitoAuthorizer:
          UserPoolArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}"
          Identity:
            Headers:
              - Authorization
        LambdaAuthorizer:
          FunctionPayloadType: TOKEN
          FunctionArn: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AdministratorsLambdaAuthorizer}"
          Identity:
            Headers:
              - Authorization
    TracingEnabled: true

Resources:
  CustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Timeout: 10
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Customer:
          Type: Api
          Properties:
            Method: any
            Path: /{proxy+}
