AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Cognito User Pool (uksb-1tthgi812) (tag:cognito-user-pool)

Globals:
  Function:
    Runtime: python3.12
    CodeUri: src/

Parameters:
  ApiGateway:
    Type: String
    Description: API Gateway ID

  ApiGatewayCognitoAuthorizer:
    Type: String
    Description: API Gateway Cognito Authorizer ID
  
  ApiGatewayRootResourceId:
    Type: String
    Description: API Gateway Root Resource ID


Resources:
  # Define the Lambda function
  CustomerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler  # Update to match your actual handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 30

  # Permission for API Gateway to invoke the Lambda function
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CustomerLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/customer

  ApiGatewayMethodCustomer:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiGatewayCognitoAuthorizer
      HttpMethod: ANY
      ResourceId: !Ref ApiGatewayResourceCustomer
      RestApiId: !Ref ApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt CustomerLambdaFunction.Arn
      MethodResponses:
        - StatusCode: 200

  ApiGatewayResourceCustomer:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayRootResourceId
      PathPart: customer
      RestApiId: !Ref ApiGateway

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod
    DependsOn:
      - ApiGatewayMethodCustomer

Outputs:
  CustomerEndpoint:
    Description: Customer API Endpoint
    Value: !Sub "https://${!ImportValue ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/customer/"

